INSERT INTO greenfit.activity (id, name, met_score) VALUES (1, 'Ball hockey', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (2, 'Ballroom dancing', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (3, 'Baseball', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (4, 'Basketball', 11.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (5, 'Bicycling (10 km/h)', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (6, 'Bicycling (15 km/h)', 5.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (7, 'Bicycling (20 km/h)', 7.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (8, 'Bicycling (25 km/h)', 8.4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (9, 'Bicycling (30 km/h)', 9.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (10, 'Bocce', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (11, 'Body building', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (12, 'Bowling', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (13, 'Boxing', 13.4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (14, 'Broomball', 6.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (15, 'Canoeing', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (16, 'Car driving', 2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (17, 'Catch (ball)', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (18, 'Cricket', 6.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (19, 'Croquet', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (20, 'Cross-country skiing (4 km/h)', 5.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (21, 'Cross-country skiing (6 km/h)', 7.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (22, 'Cross-country skiing (8 km/h)', 9.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (23, 'Cross-country skiing (10 km/h)', 12.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (24, 'Cross-country skiing (12 km/h)', 14.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (25, 'Cross-country skiing (14 km/h)', 16.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (26, 'Curling', 7.4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (27, 'Disco and popular dancing', 5.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (28, 'Equestrianism', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (29, 'Exercise classes', 6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (30, 'Fencing', 8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (31, 'Figure skating', 12.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (32, 'Fishing from bank', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (33, 'Fishing in stream', 3.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (34, 'Fishing from boat', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (35, 'Floor hockey', 10.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (36, 'Folk dancing', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (37, 'Football (American)', 6.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (38, 'Football (touch)', 7.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (39, 'Freestyle skiing', 6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (40, 'Frisbee', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (41, 'Golf, carrying clubs', 5.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (42, 'Golf, pulling cart', 3.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (43, 'Golf, riding cart', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (44, 'Gymnastics', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (45, 'Handball', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (46, 'Hiking', 6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (47, 'Home calisthenics', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (48, 'Horseback riding, walk', 3.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (49, 'Horseback riding, trot', 6.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (50, 'Horseback riding, gallop', 8.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (51, 'Horseshoes', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (52, 'Hunting', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (53, 'Ice hockey', 12.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (54, 'Jogging (9 km/h)', 8.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (55, 'Jogging (11 km/h)', 11.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (56, 'Judo', 10.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (57, 'Karate', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (58, 'Kayaking (12.5 km/h)', 7.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (59, 'Kayaking (15 km/h)', 11);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (60, 'Lacrosse', 12.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (61, 'Modem dancing', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (62, 'Motorcycling', 2.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (63, 'Mountaineering', 7.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (64, 'Orienteering', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (65, 'Racquetball', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (66, 'Ringette', 12.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (67, 'Rollerskating (12.9 km/h)', 5.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (68, 'Rollerskating (13.9 km/h)', 7.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (69, 'Rollerskating (16.9 km/h)', 9.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (70, 'Rollerskating (17.9 km/h)', 10.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (71, 'Rope skipping (66/min)', 9.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (72, 'Rope skipping (84/min)', 10.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (73, 'Rope skipping (100/min)', 11);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (74, 'Rope skipping (120/min)', 11.4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (75, 'Rope skipping (125/min)', 11.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (76, 'Rope skipping (130/min)', 11.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (77, 'Rope skipping (135/min)', 12);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (78, 'Rope skipping (145/min)', 12.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (79, 'Rowing (4 km/h)', 5.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (80, 'Rowing (8 km/h)', 10.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (81, 'Rowing (12 km/h)', 13.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (82, 'Rowing (16 km/h)', 16.4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (83, 'Rowing (20 km/h)', 19.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (84, 'Rugby', 12.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (85, 'Running (13 km/h)', 12.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (86, 'Running (15 km/h)', 14.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (87, 'Sailing (small boat)', 3.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (88, 'Scuba diving', 11);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (89, 'Sculling', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (90, 'Skateboarding', 6.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (91, 'Iceskating (18 km/h)', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (92, 'Iceskating (25 km/h)', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (93, 'Iceskating (28 km/h)', 9.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (94, 'Iceskating (32 km/h)', 10.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (95, 'Iceskating (36 km/h)', 15.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (96, 'Snorkeling', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (97, 'Snowmobiling', 2.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (98, 'Snowshoeing (4 km/h)', 9.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (99, 'Soccer', 10.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (100, 'Softball', 3.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (101, 'Squaredancing', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (102, 'Squash', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (103, 'Swimming (beach)', 3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (104, 'Swimming (pool) (2 km/h)', 4.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (105, 'Swimming (pool) (2.5 km/h)', 6.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (106, 'Swimming (pool) (3 km/h)', 8.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (107, 'Swimming (pool) (3.5 km/h)', 11.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (108, 'Swimming (pool) (4 km/h)', 13.6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (109, 'Synchronized swimming legs only', 8.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (110, 'Synchronized swimming arms only', 9.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (111, 'Table tennis', 4.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (112, 'Tag games', 4);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (113, 'Tennis', 4.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (114, 'Tennis doubles', 4.5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (115, 'Tobogganing', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (116, 'Marathon', 13.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (117, 'High jump', 4.1);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (118, 'Long jump', 15);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (119, 'Shot put', 3.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (120, 'Trail biking', 7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (121, 'Volleyball', 6);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (122, 'Walking for exercise (3 km/h)', 1.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (123, 'Walking for exercise (5 km/h)', 3.2);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (124, 'Walking for exercise (7 km/h)', 5.3);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (125, 'Walking upstairs', 4.7);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (126, 'Waterpolo', 9.8);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (127, 'Waterskiing', 7.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (128, 'Weightlifting', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (129, 'Weight training', 10.9);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (130, 'Windsurfing', 5);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (131, 'Wrestling', 10);
INSERT INTO greenfit.activity (id, name, met_score) VALUES (132, 'Yoga', 3.2);
